name: "Build and/or Deploy Docs"
description: "A composite action to build and/or deploy documentation."

inputs:
  docs_deploy_token:
    description: "Token used to deploy the docs."
    required: false
  update_docs:
    description: "Set to 'true' to push the changes to the docs repository or 'false' to skip updating."
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Build docs
      shell: bash
      run: |
        (while true; do echo "Heartbeat: $(date)"; sleep 30; done) &
        echo_loop_pid=$!

        # Ensure the heartbeat is stopped on exit, even if make html fails.
        trap "kill $echo_loop_pid" EXIT

        cd docs
        make clean; nice -n 10 make html
        
        # save the version to as an output of the step
        VERSION=$(python -c "import hidet; print(hidet.__version__)")
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Deploy docs
      env:
        DOCS_DEPLOY_TOKEN: ${{ inputs.docs_deploy_token }}
        UPDATE_DOCS: ${{ inputs.update_docs }}
      shell: bash
      run: |
        if [ "$UPDATE_DOCS" = "true"]; then
          echo "Deploying docs for version: $INPUT_VERSION"

          git config --global user.email "Hidet CI"
          git config --global user.name "Hidet CI"
          git clone https://hidetCI:${DOCS_DEPLOY_TOKEN}@github.com/hidet-org/hidet-org.github.io
          cp -r ./build/html/ hidet-org.github.io/html/docs/${VERSION}
          cd hidet-org.github.io/html/docs/

          if [ "$VERSION" != "nightly" ]; then
            rm -f stable && ln -s -T ${VERSION} stable
          fi

          git add . && git commit -m "Update docs ${VERSION}" || echo "No changes to commit"
          git push origin main

          cd ../../.. && rm -rf hidet-org.github.io
        else
          echo "Skipping deployment as per configuration (update_docs: $UPDATE_DOCS)."
        fi
