name: "Build and/or Deploy Docs"
description: "A composite action to build and/or deploy documentation."

inputs:
  docs_deploy_token:
    description: "Token used to deploy the docs."
    required: false
  version:
    description: "Optional version string to deploy the docs to. For nightly builds, use 'nightly'. For stable releases, use v{VERSION_NUMBER}"
    required: false
    default: ""
  update_docs:
    description: "Set to 'true' to push the changes to the docs repository or 'false' to skip updating."
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install dependencies via apt
      shell: bash
      run: |
        apt update && DEBIAN_FRONTEND=noninteractive apt install -y ccache git graphviz

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: "3.19.x"

    - name: Setup Hidet
      uses: ./.github/actions/setup-hidet

    - name: Install docs dependencies
      shell: bash
      run: pip install -r docs/requirements.txt

    - name: Build docs
      shell: bash
      run: |
        (while true; do echo "Heartbeat: $(date)"; sleep 30; done) &
        echo_loop_pid=$!

        cd docs
        make clean; nice -n 10 make html

        kill $echo_loop_pid
    - name: Deploy docs
      env:
        DOCS_DEPLOY_TOKEN: ${{ inputs.docs_deploy_token }}
        INPUT_VERSION: ${{ inputs.version }}
        UPDATE_DOCS: ${{ inputs.update_docs }}
      shell: bash
      run: |
        if [ "$UPDATE_DOCS" = "true"]; then
          echo "Deploying docs for version: $INPUT_VERSION"

          git config --global user.email "Hidet CI"
          git config --global user.name "Hidet CI"
          git clone https://hidetCI:${DOCS_DEPLOY_TOKEN}@github.com/hidet-org/hidet-org.github.io
          cp -r ./build/html/ hidet-org.github.io/html/docs/${VERSION}
          cd hidet-org.github.io/html/docs/

          if [ "$VERSION" != "nightly" ]; then
            rm -f stable && ln -s -T ${VERSION} stable
          fi

          git add . && git commit -m "Update docs ${VERSION}" || echo "No changes to commit"
          git push origin main

          cd ../../.. && rm -rf hidet-org.github.io
        else
          echo "Skipping deployment as per configuration (update_docs: $UPDATE_DOCS)."
        fi
