name: 'Build wheel'
description: 'Build a wheel with given version label'
outputs:
  wheel_path:
    description: 'the path to the generated wheel'
  wheel_name:
    description: 'the full name of the wheel file'
runs:
  using: 'docker'
  image: '../../../scripts/wheel/dockerfiles/manylinux_2_28_x86_64/Dockerfile'
  args:
    - "bash"
    - "./.github/scripts/build_wheel.sh"
