name: 'Build Base Docker Image'
description: 'Build and Push Base Docker Image to GCP Artifact Registry'
inputs:
  tag:
    description: 'docker image tag'
    required: false
    default: 'latest'
  gcp_secret:
    description: 'GCP secret for authentication'
    required: true
outputs:
  image_path:
    description: 'the name of the docker image with full path'
    value: 'us-east4-docker.pkg.dev/github-workflow-runners/hidet-base-ci/hidet-base-ci:${{ inputs.tag }}'
runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ inputs.gcp_secret }}'

    - name: Configure Docker for Artifact Registry
      shell: bash
      run: |
        gcloud auth configure-docker us-east4-docker.pkg.dev

    - name: Build Docker image
      shell: bash
      run: |
        docker build -f ./.github/base-image/Dockerfile -t us-east4-docker.pkg.dev/github-workflow-runners/hidet-base-ci/hidet-base-ci:${{ inputs.tag }} .

    - name: Push to Artifact Registry
      shell: bash
      run: |
        docker push us-east4-docker.pkg.dev/github-workflow-runners/hidet-base-ci/hidet-base-ci:${{ inputs.tag }}
