name: 'Setup Hidet'
description: 'Install dependencies, build and install wheel'
runs:
  using: "composite"
  steps:
    - name: Install dependencies via pip
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision torchaudio 

    - name: Build hidet
      shell: bash
      run: |
        bash scripts/wheel/build_wheel.sh
        WHEEL=$(find ./scripts/wheel/built_wheel -maxdepth 1 -name '*.whl')
        echo $WHEEL
        echo "WHEEL_NAME=$WHEEL" >> $GITHUB_ENV

    - name: Install hidet
      shell: bash
      env:
        WHEEL_NAME: ${{ env.WHEEL_NAME }}
      run: |
        pip install --force-reinstall ${WHEEL_NAME}[dev]
