name: 'Run Tests'
description: 'Runs test suite on a specified GPU'
inputs:
  wheel_name:
    description: "The name of the wheel"
    required: true
  path:
    description: "The path to the tests"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install dependencies via apt
      shell: bash
      run: |
        apt update && DEBIAN_FRONTEND=noninteractive apt install -y ccache git graphviz

    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Download wheel
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.wheel_name }}

    - name: Setup Hidet from Wheel
      shell: bash
      run: |
        pip install ${{ inputs.wheel_name }}[dev]

    - name: List installed packages
      shell: bash
      run: |
        pip list

    - name: Run tests
      shell: bash
      run: |
        (while true; do echo "Heartbeat: $(date)"; sleep 30; done) &
        echo_loop_pid=$!

        # Ensure the heartbeat is stopped on exit, even if pytest fails.
        trap "kill $echo_loop_pid" EXIT

        rm -rf ~/.config/hidet
        nice -n 10 python -m pytest -v --durations=20 --clear-cache ${{ inputs.path }}

        # Fix of https://github.com/CentML/hidet/issues/928
        python .github/scripts/cuda_cleanup.py
