name: 'Run Tests'
description: 'Runs test suite on a specified GPU'
inputs:
  wheel_name:
    description: "The name of the wheel"
    required: true
  path:
    description: "The path to the tests"
    required: true
runs:
  using: "composite"
  steps:
    - name: Run tests
      shell: bash
      run: |
        (while true; do echo "Heartbeat: $(date)"; sleep 30; done) &
        echo_loop_pid=$!

        # Ensure the heartbeat is stopped on exit, even if pytest fails.
        trap "kill $echo_loop_pid" EXIT

        rm -rf ~/.config/hidet
        nice -n 10 python -m pytest -v --durations=20 --clear-cache ${{ inputs.path }}

        # Fix of https://github.com/CentML/hidet/issues/928
        python .github/scripts/cuda_cleanup.py
