name: Tests

on:
  push:
    branches: [main]

  pull_request:
  workflow_call:
  workflow_dispatch:
    inputs:
      gpu_l4:
        description: Run Tests on L4 GPU
        type: boolean
        required: false
        default: true
      gpu_h100:
        description: Run Tests on H100 GPU
        type: boolean
        required: false
        default: true
      gpu_a10:
        description: Run Tests on A10 GPU
        type: boolean
        required: false
        default: false
      gpu_a100:
        description: Run Tests on A100-80 GPU
        type: boolean
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:

  set_gpu_params:
    runs-on: ubuntu-latest
    outputs:
      gpu_l4: ${{ steps.set_params.outputs.gpu_l4 }}
      gpu_h100: ${{ steps.set_params.outputs.gpu_h100 }}
      gpu_a10: ${{ steps.set_params.outputs.gpu_a10 }}
      gpu_a100: ${{ steps.set_params.outputs.gpu_a100 }}
    steps:
      - name: Set Parameter Values Based on Trigger
        id: set_params
        shell: bash
        run: |
          echo "Triggered by event: $GITHUB_EVENT_NAME"
          if [ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]; then
            echo "Using manual dispatch inputs"
            GPU_L4="${{ github.event.inputs.gpu_l4 }}"
            GPU_H100="${{ github.event.inputs.gpu_h100 }}"
            GPU_A10="${{ github.event.inputs.gpu_a10 }}"
            GPU_A100="${{ github.event.inputs.gpu_a100 }}"
          elif [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            echo "Using pull request defaults"
            # Set PR-specific defaults
            GPU_L4="true"
            GPU_H100="true"
            GPU_A10="false"
            GPU_A100="false"
          elif [ "$GITHUB_EVENT_NAME" == "schedule" ]; then
            echo "Using scheduled run defaults"
            # Set schedule-specific defaults
            GPU_L4="true"
            GPU_H100="true"
            GPU_A10="true"
            GPU_A100="true"
          else
            echo "Unknown event type. Exiting."
            exit 1
          fi

          # Write the parameters to GITHUB_OUTPUT so they can be used in later steps
          echo "gpu_l4=$GPU_L4" >> $GITHUB_OUTPUT
          echo "gpu_h100=$GPU_H100" >> $GITHUB_OUTPUT
          echo "gpu_a10=$GPU_A10" >> $GITHUB_OUTPUT
          echo "gpu_a100=$GPU_A100" >> $GITHUB_OUTPUT

  build-wheel:
    outputs:
      wheel_name: ${{ steps.build_step.outputs.wheel_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Get the version
        id: get_version
        run: echo "VERSION=0.0.1.dev${{ github.run_id }}" >> $GITHUB_OUTPUT

      - name: Build Hidet Wheel
        id: build_step
        uses: ./.github/actions/build-wheel
        with:
          version: ${{ steps.get_version.outputs.VERSION }}

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build_step.outputs.wheel_name }}
          path: ${{ steps.build_step.outputs.wheel_path }}
          retention-days: 3
          if-no-files-found: "error"

  build-docs-l4:
    if: ${{ needs.set_gpu_params.outputs.gpu_l4 == 'true' }}
    name: build-docs (l4)
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}-l4
      cancel-in-progress: true
    needs: [set_gpu_params]
    timeout-minutes: 120
    runs-on:
      group: arc-l4
    container:
      image: nvidia/cuda:12.6.2-devel-ubuntu22.04
      options: --gpus all
    steps:
        - name: Checkout source
          uses: actions/checkout@v4
        - name: Build docs
          id: build_step
          uses: ./.github/actions/build-docs

  build-docs-h100:
    if: ${{ needs.set_gpu_params.outputs.gpu_h100 == 'true' }}
    name: build-docs (h100)
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}-h100
      cancel-in-progress: true
    needs: [set_gpu_params]
    timeout-minutes: 120
    runs-on:
      group: arc-h100
    container:
      image: nvidia/cuda:12.6.2-devel-ubuntu22.04
      options: --gpus all
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Build docs
        id: build_step
        uses: ./.github/actions/build-docs

  build-docs-a10:
    if: ${{ needs.set_gpu_params.outputs.gpu_a10 == 'true' }}
    name: build-docs (a10)
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}-a10
      cancel-in-progress: true
    needs: [set_gpu_params]
    timeout-minutes: 120
    runs-on:
      group: arc-a10
    container:
      image: nvidia/cuda:12.6.2-devel-ubuntu22.04
      options: --gpus all
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Build docs
        id: build_step
        uses: ./.github/actions/build-docs

  build-docs-a100:
    if: ${{ needs.set_gpu_params.outputs.gpu_a100 == 'true' }}
    name: build-docs (a100)
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}-a100
      cancel-in-progress: true
    needs: [set_gpu_params ]
    timeout-minutes: 120
    runs-on:
      group: arc-a100-80
    container:
      image: nvidia/cuda:12.6.2-devel-ubuntu22.04
      options: --gpus all
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Build docs
        id: build_step
        uses: ./.github/actions/build-docs

  list-test-dirs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Hidet
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - id: set-matrix
        run: |
          python .github/scripts/set_test_matrix.py

  run-test-l4:
    if: ${{ needs.set_gpu_params.outputs.gpu_l4 == 'true' }}
    name: ${{ matrix.path }} (l4)
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}-${{ matrix.path }}-l4
      cancel-in-progress: true
    needs: [list-test-dirs, build-wheel, set_gpu_params]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.list-test-dirs.outputs.matrix) }}
    runs-on:
      group: arc-l4
    container:
      image: nvidia/cuda:12.6.2-devel-ubuntu22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        id: run_tests_l4
        uses: ./.github/actions/run-tests
        with:
          wheel_name: ${{ needs.build-wheel.outputs.wheel_name }}
          path: ${{ matrix.path }}

  run-test-h100:
    if: ${{ needs.set_gpu_params.outputs.gpu_h100 == 'true' }}
    name: ${{ matrix.path }} (h100)
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}-${{ matrix.path }}-h100
      cancel-in-progress: true
    needs: [list-test-dirs, build-wheel, set_gpu_params]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.list-test-dirs.outputs.matrix) }}
    runs-on:
      group: arc-h100
    container:
      image: nvidia/cuda:12.6.2-devel-ubuntu22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        id: run_tests_h100
        uses: ./.github/actions/run-tests
        with:
          wheel_name: ${{ needs.build-wheel.outputs.wheel_name }}
          path: ${{ matrix.path }}

  run-test-a100:
    if: ${{ needs.set_gpu_params.outputs.gpu_a100 == 'true' }}
    name: ${{ matrix.path }} (a100-80)
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}-${{ matrix.path }}-a100-80
      cancel-in-progress: true
    needs: [list-test-dirs, build-wheel, set_gpu_params]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.list-test-dirs.outputs.matrix) }}
    runs-on:
      group: arc-a100-80
    container:
      image: nvidia/cuda:12.6.2-devel-ubuntu22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        id: run_tests_a100
        uses: ./.github/actions/run-tests
        with:
          wheel_name: ${{ needs.build-wheel.outputs.wheel_name }}
          path: ${{ matrix.path }}

  run-test-a10:
    if: ${{ needs.set_gpu_params.outputs.gpu_a10 == 'true' }}
    name: ${{ matrix.path }} (a10)
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}-${{ matrix.path }}-a10
      cancel-in-progress: true
    needs: [list-test-dirs, build-wheel, set_gpu_params]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.list-test-dirs.outputs.matrix) }}
    runs-on:
      group: arc-a10
    container:
      image: nvidia/cuda:12.6.2-devel-ubuntu22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        id: run_tests_a10
        uses: ./.github/actions/run-tests
        with:
          wheel_name: ${{ needs.build-wheel.outputs.wheel_name }}
          path: ${{ matrix.path }}

  run-test-amdgpu:
    if: |
      (github.event.pull_request &&
      (contains(github.event.pull_request.body, '$ hidet-ci amdgpu') ||
      contains(github.event.pull_request.comments.*.body, '$ hidet-ci amdgpu')))
    needs: [build-wheel]
    runs-on:
      # on self-hosted runner
      [self-hosted, rocm]
    container:
      # see https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/docker.html#docker-access-gpus-in-container
      # for running AMD GPU applications in Docker containers
      image: rocm/dev-ubuntu-22.04
      options: --device /dev/kfd --device /dev/dri --security-opt seccomp=unconfined
    steps:
      - name: Install dependencies via apt
        run: |
          apt update && DEBIAN_FRONTEND=noninteractive apt install -y ccache git graphviz

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Download wheel
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-wheel.outputs.wheel_name }}

      - name: Setup Hidet from Wheel
        run: |
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm6.2
          pip install -r requirements-dev.txt
          pip install ${{ needs.build-wheel.outputs.wheel_name }}

      - name: List installed packages
        run: |
          pip list

      - name: Run tests
        run: |
          rm -rf ~/.config/hidet
          python -m pytest -v --durations=20 --clear-cache tests

  final-status-indicator:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Pass All Functional Tests
    needs: [run-test-l4, run-test-amdgpu]
    steps:
      - run: exit 1
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
          }}
