name: Upload Development Wheel to GCS

permissions:
  contents: read
  id-token: write  # Needed for auth with Google Cloud

on:
  schedule:
    - cron: '0 7 * * *'  # Runs at 3:00 AM ET (7:00 AM UTC)
  workflow_dispatch:

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    if: github.repository == 'hidet-org/hidet' || github.event_name == 'workflow_dispatch'
    outputs:
      wheel_name: ${{ steps.build_step.outputs.wheel_name }}
      wheel_path: ${{ steps.build_step.outputs.wheel_path }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # we need the full history and tags for versioning
          fetch-tags: 'true'

      - name: Build Hidet Wheel
        id: build_step
        uses: ./.github/actions/build-wheel

      - name: Upload wheel as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build_step.outputs.wheel_name }}
          path: ${{ steps.build_step.outputs.wheel_path }}
          retention-days: 7
          if-no-files-found: "error"
      
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.HIDET_DEV_WHEEL_GCP_SA_KEY }}
          
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.HIDET_DEV_WHEEL_GCP_PROJECT_ID }}
          
      - name: Upload wheel to GCS
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: ${{ steps.build_step.outputs.wheel_path }}
          destination: ${{ secrets.HIDET_DEV_WHEEL_GCS_BUCKET_NAME }}/whl/hidet/
          parent: false 
          
      - name: Generate index.html for pip compatibility
        run: |
          # Create a temporary directory for the index
          mkdir -p temp_index
          
          # List all wheel files in the bucket
          gsutil ls gs://${{ secrets.HIDET_DEV_WHEEL_GCS_BUCKET_NAME }}/whl/hidet/*.whl > wheel_list.txt
          
          # Generate index.html with links to all wheels
          echo "<!DOCTYPE html>" > temp_index/index.html
          echo "<html>" >> temp_index/index.html
          echo "<body>" >> temp_index/index.html
          echo "<h1></h1>" >> temp_index/index.html
          
          while read wheel_url; do
            wheel_name=$(basename "$wheel_url")
            echo "<a href=\"$wheel_name\">$wheel_name</a><br/>" >> temp_index/index.html
          done < wheel_list.txt
          
          echo "</body>" >> temp_index/index.html
          echo "</html>" >> temp_index/index.html
          
          # Upload the index.html to the bucket
          gsutil cp temp_index/index.html gs://${{ secrets.HIDET_DEV_WHEEL_GCS_BUCKET_NAME }}/whl/hidet/index.html
          
          # Clean up
          rm -rf temp_index wheel_list.txt 
